#!/usr/bin/env python3
"""Generate a status-report comment from ONBOARDING.md for the CNCF onboarding issue.

The CNCF onboarding issue asks projects to "Quote reply" the original checklist
and update it as items complete. This renders a matching checklist (grouped by
the same categories) with evidence links, ready to paste as a comment.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ITEMS_FILE = ROOT / ".github" / "onboarding-items.json"
ONBOARDING_FILE = ROOT / "ONBOARDING.md"
OUTPUT_FILE = ROOT / "ONBOARDING-STATUS.md"

CHECKLIST_LINE = re.compile(r"^- \[([ xX])\].*<!-- checklist:([a-z0-9-]+) -->(.*)$")
EVIDENCE_HEADING = re.compile(r"^\*\*Evidence:\*\*\s*$")
ITEM_HEADING = re.compile(r"^### ([a-z0-9-]+)\s*$")
ANY_HEADING = re.compile(r"^#{1,6}\s")


def parse_onboarding(text: str):
    """Return {slug: {"checked": bool, "tracking": str, "evidence": str}}."""
    results = {}
    current_slug = None
    collecting_evidence = False
    evidence_lines: list[str] = []

    def flush():
        if current_slug is not None:
            results[current_slug]["evidence"] = "\n".join(evidence_lines).strip()

    for line in text.splitlines():
        heading = ITEM_HEADING.match(line)
        if heading:
            flush()
            current_slug = heading.group(1)
            results[current_slug] = {"checked": False, "tracking": "", "evidence": ""}
            collecting_evidence = False
            evidence_lines = []
            continue

        if current_slug is None:
            continue

        # A category heading (## ...) ends the current item's evidence block
        # even though it isn't itself a new item heading (### ...).
        if ANY_HEADING.match(line):
            collecting_evidence = False
            continue

        match = CHECKLIST_LINE.match(line)
        if match:
            results[current_slug]["checked"] = match.group(1).lower() == "x"
            results[current_slug]["tracking"] = match.group(3).strip()
            continue

        if EVIDENCE_HEADING.match(line.strip()):
            collecting_evidence = True
            continue

        if collecting_evidence:
            stripped = line.strip()
            if stripped and not (stripped.startswith("_") and stripped.endswith("_")):
                evidence_lines.append(stripped)

    flush()
    return results


def render_report(data: dict, statuses: dict) -> str:
    lines = ["<!-- Generated by ./scripts/generate-status-report.sh — paste as a comment on your CNCF onboarding issue -->", ""]
    lines.append(f"# Onboarding status update — {data.get('project_name', 'Project')}")
    lines.append("")

    total = 0
    done = 0
    for category in data["categories"]:
        lines.append(f"## {category['heading']}")
        lines.append("")
        for item in category["items"]:
            slug = item["slug"]
            status = statuses.get(slug, {})
            checked = status.get("checked", False)
            total += 1
            done += 1 if checked else 0
            box = "x" if checked else " "
            lines.append(f"- [{box}] {item['title']}")
            evidence = status.get("evidence", "")
            if evidence:
                for evidence_line in evidence.splitlines():
                    lines.append(f"  {evidence_line}")
        lines.append("")

    percent = round((done / total) * 100) if total else 0
    lines.insert(2, f"**Progress: {done} / {total} items complete ({percent}%)**")
    lines.insert(3, "")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    if not ITEMS_FILE.is_file() or not ONBOARDING_FILE.is_file():
        print("Error: run from repository root; ONBOARDING.md or onboarding-items.json missing.", file=sys.stderr)
        return 1

    data = json.loads(ITEMS_FILE.read_text())
    metadata_path = ROOT / ".github" / "project-metadata.json"
    if metadata_path.is_file():
        data["project_name"] = json.loads(metadata_path.read_text()).get("project_name", "Project")

    statuses = parse_onboarding(ONBOARDING_FILE.read_text())
    report = render_report(data, statuses)
    OUTPUT_FILE.write_text(report, encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
